'''
Solution for question 1 of Rosalind Bioinformatics stronghold
Title: Counting DNA Nucleotides
'''
dna_str="TACTATCACTTATGCCCCACCTTAAACTGGTGTTCAGTTATAGCGCGGGCTGTGCGACCAGAATTGATCCAGTATCAACAACGGTGTCAGCTACACAACTCATCGAGGGTTAGAGCAATCCCATCGGAGTTGACAATCCATACCCACATGTTCTTTAATAGACACCTTCACCCTGGCCGGAGGTATACTGACTAAGTTCGCGGTCCGGGGGCGCTCCGAATTGTGGGCATTACATAGCAGAATAGTCCGGGATGATATGCAGGATTAATATGCCTCTCTGGTTCACTATCGTATTACGAAGGCTTAATCAGTCGAGGGTAGCACAACTCTCAGGGTAAAGGTGGAAATATCCATACTTCCCCGTGATTGACCTTGCAGCACGGAGCCAAAGCAGGACAGGCCGGCTTCTTCGGAGTTCGTTAGGCCCCTTGTCTTGCCGCGCTCATCGATGAGAGGGAATTGGAAGTCTTCGGCGATGTTCGGATCCTAGCTCTCAGAAACACTGCCCCATACAGTCTATCCCAGTGTCAGAACCGAGCCCTGAGAAGCCCAGCCATGGATGGAACAGGGACGTTACTTGGCCAACGCGAACGTACCAGCCTACGTACTGTGTGCTGCTGCAGCGGGAACAGTTAGGCTTGTTGCTAGGATGGGAGCGGCAGAACTCCCCAAAAGTCCTTGTCACGTGTCCCAGATATAAGGGCGGAATAAACGCTATGGAACGACGCGGACTTCTCGCCTTTCTTGCAGCTCCCAGTTTTCAACATAGACTGTTGCATTTCTGGCCATGTTGTTAGTGACTAGTGACATCTTTGACAGAGGTCATCGCAGCCGCAACCCATGATGCTATACGTCCTCGCCCCACTAGGAATCCTACAGGGCATAATTAGAGTTCCGTGAAACGACTTTGTGTCGGTAGATCCGACTCGTCCCTAGACTCGAAATCAACGAGCCT"
'''
Previous approach: Mannual iteration
A=0,...
for x in dna_str:
  if x=="A":
    A+=1... etc
'''
#New approach: Usage of python string methods
A=dna_str.count("A")
C=dna_str.count("C")
G=dna_str.count("G")
T=dna_str.count("T")
'''
Expected output according to the question:
Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s
'''
print(f"{A} {C} {G} {T}")
# Output: 235 251 239 230
