'''
Solution for question 9 of Rosalind Bioinformatics stronghold
Title: Finding a Motif in DNA
Given two strings s and t , t is a substring of s if t is contained as a contiguous collection of symbols in s
'''
s="TCGACTTTAGGACTCTTTAGGGTGTCCTTTAGGTACTTTAGGCCTTTAGGAAACTTTAGGTCCCTTTAGGGAGACTTTAGGAGGCTTTAGGGATCCTGTCTTTAGGGTACTTTAGGTCTTTAGGCCCTCCTTTAGGACTTTAGGTTGCTTTAGGTACTTTAGGGCTTTAGGACTTTAGGTCTTTAGGGCTTTAGGACTTTAGGCTTTAGGCTTTAGGGACTTTAGGTCTTTAGGACGTCTTTAGGACCTGCTTTAGGCACTTTAGGCTTTAGGCTTTAGGCTTTAGGATCTTTAGGCTTTAGGCTTTAGGTCTCCTTTAGGCTTTAGGCTTTAGGGCTTTAGGCTCTTTAGGCTTTAGGCAGTATGCCCAGGCTTTAGGACTTTAGGCTTTAGGCGTGTGGTCCGCTTTAGGTGCAGAACTTTAGGCGGGGGCCGGCTTTAGGCTTTAGGCTTTAGGCATTCGCGTATCTTTAGGCTTTAGGCTCTTTAGGCTTTAGGCCTTTAGGTATCTTTAGGCTTTAGGCTTGAGCTTTAGGCTTTAGGCTTTAGGAACAGTGCGTGCCAACCTTTAGGGATACTACTTTAGGCTTTAGGAGCTTTAGGCTGGACTTTAGGTGGGGCGATAGCTTTAGGCTTTAGGCTTTAGGAAACTTTAGGCATCTTTAGGCTCTTTAGGCGACTCCTTTAGGCTCCCTTTAGGCCTTTAGGCATGCTTTAGGGCTTTAGGTAGCCTTTAGGTCTTTAGGCTTTAGGCGCTTTAGGTCTTTAGGCTTTAGGTCTTTAGGCTTTAGGCTTTAGGGCTTTAGGGACTTTAGGCTCTTTAGGCATGCTTTAGGGTGCTTTAGGTATCTTTAGGATTGGACTACCGGCCCTTTAGGAACCTTTAGGCCTTTAGGCTCTTTAGGCTTTAGGTGCGCTTTAGGCTTTAGGAATGAGCTTTAGGCTTTAGGACTTTAGG"
t="CTTTAGGCT"

'''
Expected output:
Return all locations of t as a substring of s
'''
locations=[]
start_location=0

while True:
  location=s.find(t, start_location)
  if location== -1:
    break
  locations.append(location+1)
  start_location= location +1
print(*locations)

'''
Output:
197 204 260 267 274 290 297 315 322 337 346 381 437 444 469 476 485 510 517 530 537 581 597 627 634 661 683 740 764 779 786 810 890 899 917 937
'''
