
'''
Solution for question 17 of Rosalind Bioinformatics stronghold
Title: Inferring mRNA from Protein
Given:  A protein string
'''

'''
Expected Output:
The total number of different RNA strings from which the protein could have been
translated, modulo 1,000,000. (Don't neglect the importance of the stop codon
in protein translation.)
'''

codon_freq_dict = {
    'A': 4, 'C': 2, 'D': 2, 'E': 2, 'F': 2,
    'G': 4, 'H': 2, 'I': 3, 'K': 2, 'L': 6,
    'M': 1, 'N': 2, 'P': 4, 'Q': 2, 'R': 6,
    'S': 6, 'T': 4, 'V': 4, 'W': 1, 'Y': 2
}


given_pro="MGVWNWWAWDDCPNGSNDEFHYDTQIEMEFYYTIYTSWGLIDPSYFIKPYKPKWFAQIKQKPFAYVACHVHWETTGDMLWTQDLEGLTGIVNVYTNWNETRMTTYTPTRAIEIDCWAESMLCLAEAETLIQPSCNGDNRAFCKSTEGDVVANMMSFSIAGSWWKRGKIHWDQTRRVWTSRQTLSIDFIWVAGTYNKIIDCPNFYEVSQQVRHSFQTILDRPQKATQIGNCVNFFIWRADQAENQLRNWMDAVWKDKHESTRHPEEKYAEYPIPAQCVYGGKRIRIYWLNCPPVWIWLERFYIYCQNEDRYYPYITHQYFNIQGLYHAYLPLWAYWVDTPQVQSWDAPDIYNKWMTNLNPREFNQCMCCIRIFTAMSDTWVARAHPKQGFNWELFMEEEIYMGEIEFSDKTYNRCYHDYPISCDTIAKLFEQFFISGFTDVGNAKRFTCFSTSIENMRWGLCTCHRVMWRVRWFSNDGWESRNPYGVPVLANSQWHKEAPSKWQCGLCWGIHFRLESAWKNTQNLIKQTFSLWMMIKRPFDQALHEAYAGFLTKSMKYAMNVEWSAPQTIKSRYFGNMSHNDHANVASFENRGIKTQRWGTIWWSTAGLQKFWFPTHAWDYLETQPYHGCDNFEWNKEMTLLAFYLMIKLCEAYYLAPMTCAKFMSDERFCFKDFTCQLIMILLLGRLVSSRLVLANPADQWHGFFKKKTPCQSHTPHYSSDQECKEQAWGIREWWAFAHTSHMPAKTHMKHCVHEELGIASALDMVVNSLGFDPGIIDKRWFQIGDVWQWFHDRPSYANESNSFMTSQEFKFGSCRYHNRPIKKGCNIWSKYNWGSAEIRIGSCDEEYWFMESDASDIWITTFVAYKDRAQQLRGYRHKVSEMFNVNWNYNRSCCINTNAQIIQVTDCEYFIAGETAARHKLQTMFVDNHVAMANNSPIYFVHAQSNYRMLLVGLCKNPQDIPALMECRAEEHVYPWIPKEWVQKVALFHFCFMLACIY"

total_rna=1

for amino_acid in given_pro:

  total_rna=(total_rna*codon_freq_dict[amino_acid]) % 1000000

total_rna=(total_rna*3)% 1000000 # 3 is the number of stop codons

print(total_rna)

#Output: 252096

