
'''
Solution for question 22 of Rosalind Bioinformatics stronghold
Title: RNA Splicing
Given: A DNA string and a collection of substrings of s
acting as introns, in FASTA format
'''


fasta=""">Rosalind_0319
ATGATTCCTCCGCCTAAATATGCTGCCGTAATAGCGAGCCATTATCAATTCGGATCCCAT
GTTCTGACTGATGCAGGCGTGCCACATCTAACCGGTTACAGTATGGCTTAGTGCGAACTC
TTCCCGGGCCAACTTGACCGTTAAGCGTCAGTAGTGGCTACGGGCGGCCCCGGTTACCAC
AGGTATCTTGAACAGCCCAGGCCACACACCCGGTGACTAATTTAATCACATGAAAGAGCT
CTCAAAGGTTGTCAAATGTTCAAAGTCAGCCTCCAAGCGATGTGGGCATTGAAAAGCAGG
TGTGGCCGAATCCATAGGCCCGAACACGAAAAAAGATGTCATACACGAGGGAACCCGAGA
AAATATCAGAAAGAGCTTGGCGCTGGTCATATCTCCCCTCTGATTATCCTCTTAAGATAC
TTTTTCGGTGTATTTTTCCGCCCCATGCCTATCAAGACTTGCTGCCCTGCATCAGAGTGA
ACGTCGTTAAACGTTTCTCTTTTTCCTGCACAATCTGCACCACTTATCGATTAGAAATCT
GAAATCTTGACCTTTATCTTCCACGGGCTACCATTTAACACCACACCCCACGCAAACATG
CACCTAAGCAGAGACTGAACATTTGGGTAGTCTATGTTTCGGGGCACCCGGTTGCCCTCC
CAGTTGTCGTCCTAAACGACATCAACCTGGCACATGACGTTCCCAGCTGATCACCTCAAT
TTATCGCGCCCGCCTATACATCAACGATTTGGTGTGTCAGCTAGTTGGGACACTCAAGAC
CAATACTGGATGCGAGTTTTTCTGAATACCGGAGACCACGCCGACCTCGCCGTTCATAAG
AACTAACCACCCTCCAACCTCTGACTATGTTTATACCATACAGTTCCCAGGCACACTGAA
CTTTTACAAGATTCGAACCAAAAGGGAGATCCGAAACCATCTTCCGGTATAGGCAATGTA
AGCTGCTAACTTGGTGGTCTCAGTAA
>Rosalind_2594
GAAAAAAGATGTCATACACGAGGGAAC
>Rosalind_4667
TCTGAATACCGGAGACCACGCCGACCTCGCCGTTC
>Rosalind_9899
ATGGCTTAGTGCG
>Rosalind_0644
GATTAGAAATCTGAAATCTTGAC
>Rosalind_4219
ATCTCCCCTCTGATTAT
>Rosalind_4486
TAACACCACACCCCACGCAAACATGCACCTAAGCAGAGACTGAACATT
>Rosalind_6041
AGAGTGAACGTCGTTA
>Rosalind_4616
TTGAAAAGCAGGTGTGGCCGA
>Rosalind_4693
ACCGTTAAGCGTCAGTAGTGGCTACGGGCGGCCCCGGTTAC
>Rosalind_1143
TCTTCCGGTAT
>Rosalind_4718
TCGCGCCCGCCTATACATCAACGATTTGGTGTGTCAGCTAG
>Rosalind_0436
TGACTAATTTAATCACATGAAAGAGCTCTCAAAGGTTGTCAAATGTTC
>Rosalind_7825
CATTATCAATTCGGATCCCATGTT
>Rosalind_8295
GACTATGTTTATACCATACAGTTCCCAGGCACACTGAACTTTTACAA
>Rosalind_3776
CCGCCCCATGCCTATCAA
>Rosalind_6830
GTTGCCCTCCCAGTTGTCGTCCTAAACGACATCAACC
"""

dna=""
sub=[]

#Extraction of dna from fasta to a string and substrings to a list

sequences=[]
sequence=""

for line in fasta.splitlines():
  if line.startswith(">"):
    if sequence!="":
      sequences.append(sequence)
    sequence=""
  else:
    sequence+=line


if sequence!="":
  sequences.append(sequence)

dna=sequences[0]
introns=sequences[1:]


for intron in introns:
  dna=dna.replace(intron,"")


DNA_CODON_TABLE = {
    'ATA':'I', 'ATC':'I', 'ATT':'I', 'ATG':'M',
    'ACA':'T', 'ACC':'T', 'ACG':'T', 'ACT':'T',
    'AAC':'N', 'AAT':'N', 'AAA':'K', 'AAG':'K',
    'AGC':'S', 'AGT':'S', 'AGA':'R', 'AGG':'R',
    'CTA':'L', 'CTC':'L', 'CTG':'L', 'CTT':'L',
    'CCA':'P', 'CCC':'P', 'CCG':'P', 'CCT':'P',
    'CAC':'H', 'CAT':'H', 'CAA':'Q', 'CAG':'Q',
    'CGA':'R', 'CGC':'R', 'CGG':'R', 'CGT':'R',
    'GTA':'V', 'GTC':'V', 'GTG':'V', 'GTT':'V',
    'GCA':'A', 'GCC':'A', 'GCG':'A', 'GCT':'A',
    'GAC':'D', 'GAT':'D', 'GAA':'E', 'GAG':'E',
    'GGA':'G', 'GGC':'G', 'GGG':'G', 'GGT':'G',
    'TCA':'S', 'TCC':'S', 'TCG':'S', 'TCT':'S',
    'TTC':'F', 'TTT':'F', 'TTA':'L', 'TTG':'L',
    'TAC':'Y', 'TAT':'Y', 'TAA':'Stop', 'TAG':'Stop',
    'TGC':'C', 'TGT':'C', 'TGA':'Stop', 'TGG':'W',
}

#Expected Output:A protein string resulting from transcribing and translating the exons

protein_str=""

for i in range(0,len(dna),3):
  codon=dna[i:i+3]
  symbol=DNA_CODON_TABLE[codon]
  if symbol=="Stop":
    break
  protein_str +=symbol

print(protein_str)


'''
Output:
MIPPPKYAAVIASLTDAGVPHLTGYSNSSRANLHRYLEQPRPHTRKVSLQAMWAIHRPEHPRKYQKELGAGHPLKILFRCIFDLLPCINVSLFPAQSAPLILYLPRATIWVVYVSGHPWHMTFPADHLNLLGHSRPILDASFIRTNHPPTSDSNQKGDPKPRQCKLLTWWSQ
'''

