
'''
Solution for question 30 of Rosalind Bioinformatics stronghold
Title: Finding a Spliced Motif
Given: Two DNA strings s and t in FASTA format.
'''

fasta=""">Rosalind_9653
TCTATTTCGCGGCGCCCCCTTAAGGCGACTGATAGAGATGACAGCGTACTTCATGAGGCA
TGAGGCCGCTTGATGATCAACCTTACGTGGACGAGTACTGTATATTGTATCGTTTTGGGG
TATGCATCCGGCGATATCTATGGTGTAACAGTCGGGCAGAAACTAACGGCCACCTAACGA
TAAGACTATATAAGGCTTTTTATTCTACGCATAAACGTTCCTGACTCTTCAAAACCAATT
CAAGTTGTTTCCCTGCTCTGGAGTAACAAGAGTAGCTTAGGTACGACAATAGGACGGTGA
GGTATTACGGAGGACAGGATCCCTCTTAACTCATGAAGGCCATCATAAGGTAATGATCTT
ACGAGTGTCGGCGGAGGTTTACGCTCTGGTCACTCTCCGGCCGAACTATAGGGCAAGGCA
GTTGTCATTATTAATTCATTAAGTTCCATCTGTCCTCTTCATTAAGGGATAGGCGGAGGC
TGTTCGCCTACTAGCCTGCACTACCATATCAGGCCGCTGTCCCCCAGATGACCATATAGT
TCAAGCATACTGTAGCCTTCGGCCTTGTCGAAAACGTAAAAACGGTAGAATTTGTTCTTG
CCTACCACTTAAGGTACCACCCGCAAGAGTGCTGAGTTCAACTTTACTCTCTAAGCTGAA
CGACCAGTGATTTTGTCTTTTCCGTCGCCAGCGTCCAGCTCCGTTTGCCCCCTTCCGCAA
TATGGAAAGGCCGCTACGCCTCTAAGCACACATAACTGTCCATCAGGAGTGCAGGTCGGC
GCCGATGAAACACCCGAGGGTTCCTTGTCTAGGGTGCCAT
>Rosalind_5121
TGGGCCGTGTGTGCTAAAAATCATTGATTTGGCAGGTATTTGCACATCCCCCCTTATGTC
CCTCCCTTACC
"""


#s is the main dna string
s=""
#t is the motif string
t=""

current_str=None

for line in fasta.splitlines():
  if line.startswith(">Rosalind_9653"):
    current_str="s"
  elif line.startswith(">Rosalind_5121"):
    current_str="t"
  elif not line.startswith(">") and current_str is not None:
    if current_str=="s":
      s+=line
    elif current_str=="t":
      t+=line

'''
Expected Output:
One collection of indices of s in which the symbols of t appear as a subsequence of s
'''

locations=[]

start_location=0

for x in t:
  found=False
  for i in range(start_location,len(s)):
    if s[i]==x:
      locations.append(i+1)
      start_location=i+1
      found=True
      break

  if not found:
    break

print(*locations)

'''
Output:
1 9 11 12 13 15 24 30 31 33 35 39 40 42 47 48 53 56 60 63 70 78 79 83 84 87 91 96 99 101 107 112 125 126 130 131 135 136 137 139 141 142 149 150 153 158 164 167 170 171 173 174 178 181 187 188 189 194 197 205 208 210 212 216 220 221 222 226 231 235 236
'''
