
'''
Solution for question 31 of Rosalind Bioinformatics stronghold
Title: Transitions and Transversions
Given: Two DNA strings s and t in FASTA format.
'''

fasta=""">Rosalind_3444
GAGTACACTGCACGGGGCGCAGGCGGACGTCCGTATCACATAACCAGGATACAGTTTATA
GATGAGACTATGTGCAACTGGAGTTGTTCGTGATCCTACCTAACCAAGCTAGACGGAATT
TTGCACGCGGCCAGAGTCGAGGGGTATAGATTAACTAGTCCGCATGTGGGCTCAAGGGTT
TGATAGCTCGTAGATAGGAAACGTTCACTTGATTTGGACTGGAATTGGCTCAAGGACTCA
AAAATGCCACGGAGCTGTATCCGTGTAGTGACTTGCGTTCGAAGCCGTCACATGCCACCC
TTCACAGCATGGCATTGGTTTGAAGGCGGGGATGACGCCCAGCAGACCCTTACACGAACT
TAACTAATGCCCGCGACAAGAATCGATATTCGGTACCAACTTTCCTAATGGTTCGACGCT
TTTCTATGGGTGACAGCCTGATTGTCTCTTCATTCATTCCGAGGAGCCCCTGTAGGAAAG
TTTCAGGTGGCCATCCATTGTGATACGGTGACCCTAGGATTAGATTTGTCATGGTTCTGA
AACGTTTTGGATTATCATATCGCTGACATGCATCGGCACGGCGAGCAGGATATAGCTTGC
TAACGAACTGTTCGGCAATGGCCATCTGTGTCGGGGCCCTAGTCGAGCGAAGACATTATG
TCCTCGAATCCAGCCCTAACGGACCGTCTCCCTACCTGCCAGGTACACCATTATCCCATT
GGAATTGTACAATGTTATAACTCGGTAGATATTGTTGCCCGGAGGACTCACTGGGGTGCC
TATGTCTCGCTGTCCATCCCCTTTATTGCAGTAGCGGATGTGTGAGCTCAACGGTCAGGA
GACCGAACTCGTCATTCACGCCACCTATTCACCAATGTGTCAGTTGCTGGTCTCATTCGA
CCAAGAGGAGAATTAGAATAATGTCTCCT
>Rosalind_5053
GGGTACGCCACGCGGGGCGCAGGCACTCGCCCTTACCTTAAACCCAGGCTACGCTCTGTA
AACGAGGTTATGTGGAACTGGGTTAGCTCGTGACTCGACTTAACCAAGCTAGGCTGAGCT
CCGCACGCGTCCAGAAGCGAAGGGTATGTATTAACTAACCCTTCCGCGGACTCAGCGGTT
TGACAACTCGAAGATGAAAAGCATTTACTCGATTTGGACTGGAACTGGCACCAAGATATA
TAGATGCCACGGATTTATACCCGTGTGGTAACTTATGGTTGGAGCCGTCGCGTTCCGGCC
TTCACAGCACGCCACTGATTTCAAGATGGGCACCAAACCCAACGGGCCTTTGCGTGAACT
CCGCGAATCCTTGCGACAAGAATCGATACTCTGTGTCAGCTGGCGTAATGATTCGATTCT
TTCCAGTGAGTGACAGCCTGTTACCTTCCTCATTTATTCCTAGGGGCCCCTGCAGGTAAG
TTCCAGGTGGCCATCTATCGTGAGACGACGATTCTAGGGTTGGACTTTTCATAGTTCTAG
AACGATCAGGATCATTCTATAGGTAATATATAACGACACGGCGAGCAGAATTTAGCTTGC
TAGTAAGAAACTGAGCAGTCCCCACCCACGTCAGGGTCCTAATTGAGCGAGGACACAATG
TCATCCCGTTCAACCCCAGTGGAAATCCTCCCTACTTGCTGGGTATACTACTACCCCATC
AGAGTTGTACGGATTTGCGACTCGTTAGACACCGTGGCCCCGAGAACCCGGTAAGGGGCC
CATGTTTCGCTGCCTGTTCCTCCCTGGGGATCAGCGGGTGCGGAAGCTCAATGGTTAGGA
GAACGGATCCGCTAACCACGCTATCTTTTCGCTAATGCGTTATTTAGTGATTTCATTCGA
CGAAGAGAAAGATCAGAGCCATGCTACAC
"""

s1=""


s2=""

current_str=None

for line in fasta.splitlines():
  if line.startswith(">Rosalind_3444"):
    current_str="s"
  elif line.startswith(">Rosalind_5053"):
    current_str="t"
  elif not line.startswith(">") and current_str is not None:
    if current_str=="s":
      s1+=line
    elif current_str=="t":
      s2+=line

#Expected Output:The transition/transversion ratio


#MAIN CODE


transition_count=0

transversion_count=0

#FINDING TOTAL TRANSITION COUNT

for x,y in zip(s1,s2):
    if x=="A":
      if y=="G":
        transition_count+=1
    if x=="G":
      if y=="A":
        transition_count+=1
    if x=="T":
      if y=="C":
        transition_count+=1
    if x=="C":
      if y=="T":
        transition_count+=1


#FINDING TOTAL TRANSVERSION COUNT

for x,y in zip(s1,s2):
    if x=="A":
      if y=="T":
        transversion_count+=1
    if x=="T":
      if y=="A":
        transversion_count+=1
    if x=="C":
      if y=="G":
        transversion_count+=1
    if x=="G":
      if y=="C":
        transversion_count+=1
    if x=="A":
      if y=="C":
        transversion_count+=1
    if x=="C":
      if y=="A":
        transversion_count+=1
    if x=="G":
      if y=="T":
        transversion_count+=1
    if x=="T":
      if y=="G":
        transversion_count+=1


ratio=transition_count/transversion_count

print(ratio)

#Output:2.2777777777777777
